title: My daily activities in a nutshell
author: tonylee
email: tonylee@onofflink.co.kr
description: > # this means to ignore newlines until "baseurl:"
 환영합니다. 대표님, & 권팀장님.
 오늘 하루의 힘들었던 짐은 여기에 모두 벗어 놓으시고
 내일 걱정도 묶어 두시고 가시면 깨끗하게 청소 해 놓겠습니다.

# social links
twitter_username: aiegoo
github_username:  onofflink

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal